version: 2

jobs:
  build-push:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: get dependencies
          command: |
            go get -d
      - run:
          name: build
          command: |
            go build
      - run:
          name: docker build
          command: |
            docker build -t honestica/minio-exporter:$CIRCLE_BUILD_NUM
